### ISSUE TITLE
Dockerfile based on the official Spark 2.3.0 image with spark-metrics and its dependencies

### ISSUE THREAD

**Issue by liyinan926** [banzaicloud/spark-metrics#14]
It would be great if you can provide a reference Dockerfile based on the official Spark 2.3.0 [image](https://github.com/apache/spark/blob/master/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/Dockerfile) with spark-metrics and its dependencies built-in. This makes it much easier for users to use this extension without having to build their own custom images.

**Comment by stoader** [comment]
Hi @liyinan926 , great idea. Will add one to the repository.

**Comment by stoader** [comment]
Hi @liyinan926, thinking on it more there is no need to create a new Dockerfile. You can use the official Spark 2.3.0 [Dockerfile](https://github.com/apache/spark/blob/branch-2.3/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/Dockerfile).

All you need is to copy the following jars:

- com.banzaicloud:spark-metrics_2.11:2.3-1.0.0
- io.prometheus:simpleclient:0.3.0
- io.prometheus:simpleclient_common:0.3.0
- io.prometheus:simpleclient_dropwizard:0.3.0
- io.prometheus:simpleclient_pushgateway:0.3.0
- io.dropwizard.metrics:metrics-core:3.1.2

  to `assembly/target/scala-$SPARK_SCALA_VERSION/jars` *prior* [building the Spark 2.3 docker images](https://spark.apache.org/docs/2.3.0/running-on-kubernetes.html#docker-images). This way you'll get spark-metrics jars included into the built image at `/opt/spark/jars`path  inside the image which is part of the class path of the driver and executor.

Please also read the _notes_ on Spark 2.3 here: https://github.com/banzaicloud/spark-metrics/blob/master/PrometheusSink.md

**Comment by liyinan926** [comment]
The reason why I think providing a reference Docker image makes sense is it avoid the need for users to create a custom Spark image simply to add the jars. It's not hard but it's better if it can be completed avoided.
