### ISSUE TITLE
Getting Executor Ids from one query

### ISSUE THREAD

**Issue by abhishekkaura** [banzaicloud/spark-metrics#25]
Is there any option in the metrics where we can retrieve the list of all executors id from one query so that I can create a variable in Grafana and use that to create graphs.

**Comment by stoader** [comment]
@abhishekkaura metrics published from executors have a label named `instance`. The value of this label is sourced from `spark.executor.id` spark conf. Also there is a label called `role` which is set to `executor` which indicates that the metrics is from an executor.

Let me know if this helps.

**Comment by abhishekkaura** [comment]
@stoader Thanks for the quick reply. That thing I got it from readme. My requirement is to get the executor ids returned from one prometheus query. For e.g. If I say executor_instances, it give me all executor ids available like 1,2,3,4... in one list which I can use to create a variable in grafana.

**Comment by lordk911** [comment]
if spark was config as dynamicAllocation , the executor number will always change also the executor id
