### ISSUE TITLE
Does 2.3-2.0.4 of the spark-metrics support the version of spark-2.2.0?

### ISSUE THREAD

**Issue by highfei2011** [banzaicloud/spark-metrics#29]
Thank you.

**Comment by stoader** [comment]
Take a look at the `Spark 2.2` section: https://github.com/banzaicloud/spark-metrics/blob/master/PrometheusSink.md

Version `2.2.1-1.0.0` supports Spark 2.2 however this version does not include the feature changes that were added later to spark-metrics 2.3+

**Comment by highfei2011** [comment]
Well, let me try .
