### ISSUE TITLE
Sink class com.banzaicloud.spark.metrics.sink.PrometheusSink cannot be instantiated

### ISSUE THREAD

**Issue by paskalka** [banzaicloud/spark-metrics#32]
Hello,
on spark 2.3.2
here is my spark-submit:
spark-submit --num-executors 3 --master yarn --deploy-mode client --files /tmp/log4j2.xml#log4j2.xml --repositories https://raw.github.com/banzaicloud/spark-metrics/master/maven-repo/releases --packages com.banzaicloud:spark-metrics_2.11:2.3-2.0.4,io.prometheus:simpleclient:0.3.0,io.prometheus:simpleclient_dropwizard:0.3.0,io.prometheus:simpleclient_pushgateway:0.3.0,io.dropwizard.metrics:metrics-core:3.1.2 --jars /tmp/metrics-core-3.1.2.jar,/tmp/simpleclient-0.3.0.jar,/tmp/simpleclient_dropwizard-0.3.0.jar,/tmp/simpleclient_pushgateway-0.3.0.jar,/tmp/spark-metrics_2.11-2.3-2.0.4.jar --conf "spark.driver.extraJavaOptions=-Dlog4j.configuration=log4j2.xml" --conf "spark.executor.extraJavaOptions=-Dlog4j.configuration=log4j2.xml" --conf "spark.metrics.conf=/tmp/metrics.properties"  --class myjob /tmp/drools-kie-spark-1.5.jar -droolsEmbedded

i put metrics.properties on each executors 

Thanks for your help

**Comment by stoader** [comment]
Can you share logs and your metrics.properties?

**Comment by paskalka** [comment]
Hi ,

1- I solved it by copying the prometheus and banzaicloud jars into  sparks
jars folder. Is it the standard way to use your product ?
2- I was thinking that by using --repositories --packages --jars in
spark-submit, i didn't need to copy them into spark jars folder

*metrics.properties:*

# Enable Prometheus for all instances by class name
*.sink.prometheus.class=com.banzaicloud.spark.metrics.sink.PrometheusSink
# Prometheus pushgateway address
*.sink.prometheus.pushgateway-address-protocol=http
*.sink.prometheus.pushgateway-address=leumi-promgrafana.northeurope.cloudapp.azure.com:9092
*.sink.prometheus.period=10
*.sink.prometheus.unit=SECONDS
*.sink.prometheus.pushgateway-enable-timestamp=false

# Support for JMX Collector (version 2.3-2.0.0 +)
*.sink.prometheus.enable-dropwizard-collector=false
*.sink.prometheus.enable-jmx-collector=true
*.sink.prometheus.jmx-collector-config=/tmp/jmxCollector.yaml
# Enable JVM metrics source for all instances by class name
*.sink.jmx.class=org.apache.spark.metrics.sink.JmxSink
*.source.jvm.class=org.apache.spark.metrics.source.JvmSource

*jmxCollector.yaml*

lowercaseOutputName: false
lowercaseOutputLabelNames: false
whitelistObjectNames: ["*:*"]


logs

com.banzaicloud.spark.metrics.sink.PrometheusSink cannot be instantiated


For the moment it's working because i copied the jars to all
executors, let me know if it's enough or you need the complete logs


Thanks and besr regards,

**Comment by stoader** [comment]
Based on others experiencing this issue on Yarn (https://github.com/banzaicloud/spark-metrics/issues/30#issuecomment-492301988) looks like that Yarn doesn't distribute these jars to the executor hosts in time thus when executors initialize metrics system these jars are not there. (Note we are running Spark on Kubernetes - Kubernetes being the cluster manager instead of Yarn - and not seeing this issue there).

Can you check the timestamp of when are these jars distributed by Yarn to executor hosts?

**Comment by paskalka** [comment]
How to find the timestamp ? I am not getting this information from the UI

**Comment by stoader** [comment]
@paskalka check Yarn logs to see when and where are the jars copied/distributed to or ssh to executor hosts and check the stats of the file.

**Comment by stoader** [comment]
@paskalka is this still an issue?

**Comment by paskalka** [comment]
no, it's ok

Thanks

**Comment by y0908105023** [comment]
how to solve it ？
![image](https://user-images.githubusercontent.com/8789291/63752040-1495be00-c8e3-11e9-8ca1-edfe11b52aba.png)
![image](https://user-images.githubusercontent.com/8789291/63752063-24150700-c8e3-11e9-9648-a1c30faca3a2.png)

**Comment by y0908105023** [comment]
I had the same problem，how did you solve it? Adding jars to spark folder?
![image](https://user-images.githubusercontent.com/8789291/63752211-6fc7b080-c8e3-11e9-9902-b4737dc06b9d.png)

**Comment by stoader** [comment]
@y0908105023 are you running Spark on EMR? If so see https://github.com/banzaicloud/spark-metrics/issues/30#issuecomment-492301988

**Comment by y0908105023** [comment]
@stoader  not spark on emr,just on yarn

**Comment by stoader** [comment]
@y0908105023 how does your `park-submit` command look like?

**Comment by y0908105023** [comment]
@stoader 
`cd /data0/spark/spark-2.2.1-bin && ./bin/spark-submit\
    --jars /data0/job/lib/spark-streaming-kafka-0-10_2.11-2.1.0.jar,/data0/job/lib/kafka-clients-0.10.2.1.jar \
    --master yarn \
    --files /data0/spark/metrics/metrics.properties \
    --conf spark.metrics.conf=metrics.properties \
    --conf spark.metrics.conf.*.sink.console.class=org.apache.spark.streaming.metrics.sink.HttpSink \
    --conf spark.metrics.conf.*.sink.console.url=url \
    --deploy-mode cluster \
    --name metric_test \
    --num-executors 5 \
    --driver-memory 2g \
    --executor-memory 2g \
    --class org.apache.spark.streaming.cache.ReduceByKeyAndCache \
    /data0/spark/metrics/lib/spark-test-1.0-SNAPSHOT.jar
`

**Comment by stoader** [comment]
See https://github.com/banzaicloud/spark-metrics/blob/master/PrometheusSink.md for how to pass packages to Spark.

In case of Spark 2.2 you need to pass:

```
--repositories https://raw.github.com/banzaicloud/spark-metrics/master/maven-repo/releases
```

```--packages com.banzaicloud:spark-metrics_2.11:2.2.1-1.0.0,io.prometheus:simpleclient:0.0.23,io.prometheus:simpleclient_dropwizard:0.0.23,io.prometheus:simpleclient_pushgateway:0.0.23,io.dropwizard.metrics:metrics-core:3.1.2```

Also I'd recommend upgrading to Spark 2.3+ and the latest version of spark-metrics library.

**Comment by y0908105023** [comment]
which version will solve this problem?

**Comment by stoader** [comment]
@y0908105023 I'd suggest using Spark 2.3+ passing ```--packages com.banzaicloud:spark-metrics_2.11:2.3-2.1.0,io.prometheus:simpleclient:0.3.0,io.prometheus:simpleclient_dropwizard:0.3.0,io.prometheus:simpleclient_pushgateway:0.3.0,io.dropwizard.metrics:metrics-core:3.1.2``` to your spark-submit command

**Comment by prcastro** [comment]
Hey @stoader I just tried your suggestion and it doesn't seem to be working. I still receive the error mentioned above. Funny thing is: the driver seem to have no problem with those packages, so if I do:

```
  --conf spark.metrics.conf.driver.sink.prometheus.class=org.apache.spark.banzaicloud.metrics.sink.PrometheusSink
```

The application runs without problems (the only problem is that I don't have executor metrics). However, if I run with:

```
  --conf spark.metrics.conf.*.sink.prometheus.class=org.apache.spark.banzaicloud.metrics.sink.PrometheusSink
```

It raises the exception. Am I using the packages in the wrong manner? How can  I solve this? Is manually copying the jars to the executor the only solution?

**Comment by stoader** [comment]
Yes you need to copy the needed jars to the hosts where executors run.

**Comment by prcastro** [comment]
I ended up just copying the jars and JMX config file to each node using a bootstrap action on EMR

**Comment by KeithTt** [comment]
Same problem here.

version: standalone spark 2.4 cluster with zk.

`metrics.properties`
```properties
# Enable Prometheus for all instances by class name
*.sink.prometheus.class=org.apache.spark.banzaicloud.metrics.sink.PrometheusSink
# Prometheus pushgateway address
*.sink.prometheus.pushgateway-address-protocol=http
*.sink.prometheus.pushgateway-address=172.16.68.11:9091
*.sink.prometheus.period=10
# Enable HostName in Instance instead of Appid (Default value is false i.e. instance=${appid})
*.sink.prometheus.enable-hostname-in-instance=true
```

`sprak-conf`
```
spark.jars  /data1/moji/soft/spark-thriftserver-2.4.0/jars/spark-metrics_2.12-2.4-1.0.6.jar
```

Should I copy the jar to all the workers? There are about 100 nodes.
