### ISSUE TITLE
missing collector-0.10.jar library for kubernetes workaround

### ISSUE THREAD

**Issue by dadez** [banzaicloud/spark-metrics#33]
in PrometheusSink.md you forgot to mention that the `collector-0.10.jar` should also be manually copied to `assembly/target/scala-2.11/jars` for avoid `ClassNotFoundException: io.prometheus.jmx.JmxCollector` error

**Comment by sancyx** [comment]
hi @dadez, thanks for spotting this, we have updated the doc https://github.com/banzaicloud/spark-metrics/pull/34.
