### ISSUE TITLE
Need Hostname value in instance key instead of app id

### ISSUE THREAD

**Issue by dahiyahimanshu** [banzaicloud/spark-metrics#35]
appid is redundant value in job and instance. we want to corelate executor and driver with spark worker. we need hostname information. Can we have optional property to enable hostname in instance instead of appId?

**Comment by stoader** [comment]
@dahiyahimanshu this has been released in version `2.3-2.1.0`

**Comment by dahiyahimanshu** [comment]
@stoader Thankyou
