### ISSUE TITLE
Can we publish the jar in some public maven repository?

### ISSUE THREAD

**Issue by dahiyahimanshu** [banzaicloud/spark-metrics#37]

**Comment by stoader** [comment]
@dahiyahimanshu we use GitHub as maven repository. All you need is to add `https://raw.github.com/banzaicloud/spark-metrics/master/maven-repo/releases` to the list of maven repositories.

**Comment by dahiyahimanshu** [comment]
Hello @stoader
Thankyou I will check with our software factory expert see if it works. Only thing is it gives me 404 when i open thorugh browser.
https://raw.githubusercontent.com/banzaicloud/spark-metrics/master/maven-repo/releases
it gives me 404: Not Found

**Comment by stoader** [comment]
Can you try to open https://raw.githubusercontent.com/banzaicloud/spark-metrics/master/maven-repo/releases/com/banzaicloud/spark-metrics_2.11/2.3-2.0.4/spark-metrics_2.11-2.3-2.0.4.pom ?

Also can you try open it using `curl https://raw.githubusercontent.com/banzaicloud/spark-metrics/master/maven-repo/releases/com/banzaicloud/spark-metrics_2.11/2.3-2.0.4/spark-metrics_2.11-2.3-2.0.4.pom -vvv` as well?

**Comment by dahiyahimanshu** [comment]
works well. Thankyou
