### ISSUE TITLE
specify job name and pushgateway relevant labels via config

### ISSUE THREAD

**Issue by rolandjohann** [banzaicloud/spark-metrics#39]
**Is your feature request related to a problem? Please describe.**

For each spark application a separate pushgateway job incl. specific labels will be created. As the pushgateway doesn't support TTL of groups we should be able to configure the push gateway sink accordingly to push metrics of the same job (lets say based on the spark app name) into the same group.

**Describe the solution you'd like to see**

Implement a configuration property for the sink that points towards a label that should be used as pushgateway job name and which labels should be part of the URL used to push to pushgateway.

I'm happy to provide a PR for this 🎉

**Describe alternatives you've considered**

* delete groups at pushgateway manually

**Comment by stoader** [comment]
Have you considered using metrics namespaces (`spark.metrics.namespace`)?

If you have a PR please let me know and we'll review it.

**Comment by dahiyahimanshu** [comment]
I am interested whenever my spark app crash it restart with new job name timestamp appended. I don`t know how i can clean up stale groups from pushgateway.
![pushgateway](https://user-images.githubusercontent.com/5242576/64749963-2a3af280-d535-11e9-9bf1-60205e51d09d.png)

**Comment by Matzz** [comment]
I think overriding just `spark.metrics.namespace` (job name) wont help here. I think common groupingKey is also required. However it is not possible to override it now:
```scala
      val groupingKey: Map[String, String] = (role, executorId) match {
        case ("driver", _) =>
          labelsMap match {
            case Some(m) => Map("role" -> role, "app_name" -> appName, "instance" -> instance) ++ m
            case _ => Map("role" -> role, "app_name" -> appName, "instance" -> instance)
          }

        case ("executor", Some(id)) =>
          labelsMap match {
            case Some(m) =>
              Map ("role" -> role,
                "number" -> id,
                "app_name" -> appName,
                "instance" -> instance) ++ m
            case _ =>
              Map ("role" -> role,
              "number" -> id,
              "app_name" -> appName,
              "instance" -> instance)
          }

        case _ => Map("role" -> role)
      }
```

**Comment by Matzz** [comment]
I think this article touch that topic - https://www.robustperception.io/common-pitfalls-when-using-the-pushgateway
```
This is particularly evident with metrics containing an instance label (which should not be going to the Pushgateway in the first place, as they are not service-level).
```
