### ISSUE TITLE
Configure sink to stop sending job as label/group-key

### ISSUE THREAD

**Issue by prcastro** [banzaicloud/spark-metrics#70]
**Is your feature request related to a problem? Please describe.**
Whenever I'm running spark-metrics on YARN, I see all metrics being tagged with `job=application_yarn_id`. This means when I restart the application I create new groups on pushgateway, increasing memory usage by a lot.

**Describe the solution you'd like to see**
A way to remove job from labels and group-keys.  For example, if we override the `job` on both `labels` and `group-key` I would expect spark-metrics not to send `application_yarn_id`

**Describe alternatives you've considered**
I tried to configure my application overriding the job group-key with no success:

```
*.sink.prometheus.group-key=job=streams"
```

**Comment by prcastro** [comment]
Seems related to https://github.com/banzaicloud/spark-metrics/issues/39 but that issue was closed

**Comment by stoader** [comment]
Can you try either setting `spark.app.id` to a fixed value like `streams` instead of `application_yarn_id` or set `spark.metrics.namespace` to `streams`. Currently, this is how you can control the value for the `job` tag.

**Comment by prcastro** [comment]
Setting `spark.metrics.namespace` solved the problem! Thanks
